# Generated by Django 4.0.10 on 2025-10-16 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0038_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTransactios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('module_code', models.CharField(max_length=25)),
                ('unique_id', models.UUIDField()),
                ('status', models.CharField(choices=[('new', 'New'), ('completed', 'Completed')], default='new', max_length=10)),
                ('tokens', models.IntegerField()),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_transactions',
            },
        ),
    ]
