# Generated by Django 4.0.10 on 2025-11-01 08:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
        ('ad', '0039_tokentransactios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokenTransactios',
            new_name='TokenTransactions',
        ),
    ]
