# Generated by Django 4.0.10 on 2025-11-03 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0040_rename_tokentransactios_tokentransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransactions',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
