# Generated by Django 4.0.10 on 2025-11-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0041_alter_tokentransactions_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransactions',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
