# Generated by Django 4.0.10 on 2025-11-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0043_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='TransactionID',
            new_name='Transaction',
        ),
    ]
