# Generated by Django 4.0.10 on 2025-11-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0044_teacher_created_date_teacher_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], default='beginner', max_length=50),
        ),
    ]
