# Generated by Django 4.0.10 on 2025-11-19 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0044_rename_transactionid_subscription_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='IsActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='PaymentStatus',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='SubscriptionID',
            new_name='subscription_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='SubscriptionType',
            new_name='subscription_type',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Transaction',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='UserID',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
