# Generated by Django 4.0.10 on 2026-01-08 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0049_course_applicants_alter_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransactions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
