# Generated by Django 4.0.10 on 2026-01-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0050_alter_tokentransactions_user'),
        ('ad', '0050_sitecontent'),
    ]

    operations = [
    ]
