# Generated by Django 4.0.10 on 2026-01-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0051_merge_20260112_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.TextField(default='unknown address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
