# Generated by Django 4.0.10 on 2026-01-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0052_coursechapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechapter',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
